#!/usr/bin/env bash

set -e

shopt -s extglob nullglob

INPUT_PATH=$(realpath "${1:?Error the path is required.}")
if [[ ! -d ${INPUT_PATH} || ! -e ${INPUT_PATH} ]]; then
    echo -e "\e[31mError: \e[0m${INPUT_PATH} is not a directory or does not exist."
    exit 1
fi
GLOB_STR=${2:-*.pdb}

files=(${INPUT_PATH}/${GLOB_STR})

echo -e "Found \e[36m${#files[@]} files\e[0m matching \e[32m${GLOB_STR}\e[0m."
