#!/usr/bin/env bash

set -e

shopt -s extglob nullglob

PATH=$(realpath ${1:?Error the path is required.})
GLOB_STR=${2:-*.pdb}

files=($PATH/$GLOB_STR)

echo -e "Found \e[36m${#files[@]} files\e[0m matching \e[32m${GLOB_STR}\e[0m."
